on:
    push:
        tags:
            - "v3*"
        paths-ignore:
            - README.md
            - CHANGELOG.md
            - .github/workflows/build.yml
            - .grenrc.yml
name: ReleaseBuild
jobs:
    buildmac:
        name: MacOSX
        runs-on: macos-latest
        steps:
            - name: Setup Python environment
              uses: actions/setup-python@v1.1.1
              with:
                python-version: 3.7.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -S
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -A
            - name: Production Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                 repo_token: "${{ secrets.GITHUB_TOKEN }}"
                 prerelease: False
                 files: release/*
    buildlinux:
        name: Linux
        needs: buildmac
        runs-on: ubuntu-18.04
        steps:
            - name: Setup Python environment
              uses: actions/setup-python@v1.1.1
              with:
                python-version: 3.7.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Linux Lib Install
              run: |
                cd $GITHUB_WORKSPACE
                bash linuxdeps.sh
            - name: Setup Environment
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -S
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -A
            - name: Production Release
              uses: svenstaro/upload-release-action@v1-release
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: release/*
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
    buildwindows:
        name: Windows
        needs: buildmac
        runs-on: windows-latest
        steps:
            - name: Setup Python environment
              uses: actions/setup-python@v1.1.1
              with:
                python-version: 3.7.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -setupenv
            - name: Build project
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -everything
            - name: VirusTotal Upload
              shell: powershell
              if: startsWith(github.ref, 'refs/tags/v3')
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -virus
            - name: Production Release
              uses: svenstaro/upload-release-action@v1-release
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: release/*
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
